apiVersion: batch/v1
kind: Job
metadata:
  name: demo-job-tejas
  namespace: nginx
spec:
  completions: 1
  parallelism: 1
  template:
    metadata:
       name: demo-job-pod
       labels:
          app: batch-task
    spec:
      containers:
      - name: batch-container
        image: busybox:latest
        command: ["sh",  "-c", "echo Hello sanket && sleep 10"]
      restartPolicy: Never
